import Head from 'next/head'
import Link from 'next/link'
const styles = {
    display:"inherit",
    width: 200,
    height: 200,
    backgroundColor: "green",
    textAlign: "center",
    link: {
        width: "100%",
        height: 40,
        backgroundColor: "yellow",
        textAlign: "center",
        display:"inherit",
    }
}
export default function HeaderView ({props}) {
    const title = `Tu Tu - ${props.title}`;
    return (
        <>
        <Head>
            {/* <title> {title} </title> */}
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
         <div style ={styles}>
            <Link href = {`/${props.linkUrl}`} style={styles.link} >Go</Link>
        </div>
        </>
    )
    
}